# Generated by Django 6.1.1 on 2026-09-24 02:50

import apps.sales_updates.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Q3 2026 Week 1-4', max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('cut_off_date', models.DateField(help_text='Final submission date for performance figures.')),
                ('weeks_count', models.PositiveSmallIntegerField(default=4, help_text='Number of reporting weeks in this period (4 or 5).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=8)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('JPY', 'Japanese Yen (¥)')], default='PHP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reporting periods',
                'ordering': ['-start_date'],
                'abstract': False,
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='SalesGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('revenue_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('orders_target', models.PositiveIntegerField(default=0)),
                ('orders_actual', models.PositiveIntegerField(default=0)),
                ('deliveries_target', models.PositiveIntegerField(default=0)),
                ('deliveries_achieved', models.PositiveIntegerField(default=0)),
                ('deliveries_on_time', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('JPY', 'Japanese Yen (¥)')], default='PHP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, help_text='Meeting whose minutes embed this snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_snapshots', to='meetings.meeting')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sales_updates.reportingperiod')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sales_updates.salesgroup')),
            ],
            options={
                'ordering': ['period__start_date', 'group__name', '-created_at'],
                'abstract': False,
                'unique_together': {('group', 'period', 'meeting')},
            },
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sales_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salesgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sales_updates.salesteam'),
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('orders_target', models.PositiveIntegerField(default=0)),
                ('deliveries_target', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('JPY', 'Japanese Yen (¥)')], default='PHP', max_length=3)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets_modified', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='sales_updates.reportingperiod')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='sales_updates.salesgroup')),
            ],
            options={
                'ordering': ['period__start_date', 'group__name'],
                'abstract': False,
                'unique_together': {('group', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliveries_planned', models.PositiveIntegerField(default=0)),
                ('deliveries_achieved', models.PositiveIntegerField(default=0)),
                ('deliveries_on_time', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_performances_modified', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_performances', to='sales_updates.reportingperiod')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_performances', to='sales_updates.salesgroup')),
            ],
            options={
                'ordering': ['period__start_date', 'group__name'],
                'abstract': False,
                'unique_together': {('group', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SalesGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Sales Representative', help_text='Role within the sales group (for display only).', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_on', models.DateField(default=apps.sales_updates.models._default_joined_on)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sales_updates.salesgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group__name', 'user__username'],
                'abstract': False,
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('orders_actual', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('JPY', 'Japanese Yen (¥)')], default='PHP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_performances', to='sales_updates.salesgroup')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_modified', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_performances', to='sales_updates.reportingperiod')),
            ],
            options={
                'ordering': ['period__start_date', 'group__name'],
                'abstract': False,
                'unique_together': {('group', 'period')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='salesgroup',
            unique_together={('team', 'code')},
        ),
        migrations.CreateModel(
            name='WeeklyCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField(help_text='1-indexed week inside the reporting period.')),
                ('committed_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('committed_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Optional, filled after week completes.', max_digits=16)),
                ('actual_profit', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_commitments', to='sales_updates.groupperformancesnapshot')),
            ],
            options={
                'ordering': ['snapshot__period__start_date', 'week_number'],
                'abstract': False,
                'unique_together': {('snapshot', 'week_number')},
            },
        ),
    ]
