from django.urls import path

from apps.meetings import views

app_name = "meetings"

urlpatterns = [
    path("", views.MeetingListView.as_view(), name="meeting_list"),
    path("<uuid:pk>/", views.MeetingDetailView.as_view(), name="meeting_detail"),
    path("new/", views.MeetingCreateView.as_view(), name="meeting_create"),
    path("<uuid:pk>/edit/", views.MeetingUpdateView.as_view(), name="meeting_update"),
    path("<uuid:pk>/archive/", views.MeetingArchiveView.as_view(), name="meeting_archive"),
    path(
        "<uuid:pk>/transition/",
        views.MeetingTransitionView.as_view(),
        name="meeting_transition",
    ),
    path(
        "<uuid:pk>/attendance/",
        views.MeetingAttendanceView.as_view(),
        name="meeting_attendance",
    ),
    path(
        "<uuid:pk>/carry-forward/",
        views.MeetingCarryForwardView.as_view(),
        name="meeting_carry_forward",
    ),
    path(
        "agenda-categories/",
        views.AgendaCategoryListView.as_view(),
        name="agenda_category_list",
    ),
    path(
        "agenda-categories/new/",
        views.AgendaCategoryCreateView.as_view(),
        name="agenda_category_create",
    ),
    path(
        "agenda-categories/<uuid:pk>/edit/",
        views.AgendaCategoryUpdateView.as_view(),
        name="agenda_category_update",
    ),
    path(
        "<uuid:meeting_pk>/agenda/new/",
        views.AgendaItemCreateView.as_view(),
        name="agenda_item_create",
    ),
    path(
        "agenda/<uuid:pk>/edit/",
        views.AgendaItemUpdateView.as_view(),
        name="agenda_item_update",
    ),
    path(
        "agenda/<uuid:pk>/delete/",
        views.AgendaItemDeleteView.as_view(),
        name="agenda_item_delete",
    ),
    path(
        "<uuid:meeting_pk>/agenda/order/",
        views.AgendaOrderSaveView.as_view(),
        name="agenda_item_order",
    ),
    path(
        "<uuid:meeting_pk>/attachments/upload/",
        views.MeetingAttachmentUploadView.as_view(),
        name="meeting_attachment_upload",
    ),
    path(
        "attachments/<uuid:pk>/delete/",
        views.MeetingAttachmentDeleteView.as_view(),
        name="meeting_attachment_delete",
    ),
    path(
        "agenda-attachments/<uuid:item_pk>/upload/",
        views.AgendaItemAttachmentUploadView.as_view(),
        name="agenda_item_attachment_upload",
    ),
    path(
        "agenda-attachments/<uuid:pk>/delete/",
        views.AgendaItemAttachmentDeleteView.as_view(),
        name="agenda_item_attachment_delete",
    ),
    path(
        "prep/dashboard/",
        views.PrepDashboard.as_view(),
        name="prep_dashboard",
    ),
    path(
        "<uuid:pk>/submissions/",
        views.DeptSubmissionStatusDetail.as_view(),
        name="dept_submission_status_detail",
    ),
    path(
        "<uuid:pk>/submissions/upsert/",
        views.DeptSubmissionUpsert.as_view(),
        name="dept_submission_upsert",
    ),
    path(
        "<uuid:pk>/minutes-editor/",
        views.MinutesEditorView.as_view(),
        name="minutes_editor",
    ),
    path(
        "<uuid:meeting_pk>/action-items/create/",
        views.ActionItemFromMinutesCreate.as_view(),
        name="action_item_from_minutes_create",
    ),
    path(
        "<uuid:pk>/preview/",
        views.MeetingPreviewView.as_view(),
        name="meeting_preview",
    ),
    path(
        "<uuid:pk>/validation/",
        views.MeetingValidationSummaryView.as_view(),
        name="meeting_validation_summary",
    ),
    path(
        "<uuid:pk>/submit-for-review/",
        views.SubmitForReviewView.as_view(),
        name="submit_for_review",
    ),
    path(
        "<uuid:pk>/return-for-correction/",
        views.ReturnForCorrectionView.as_view(),
        name="return_for_correction",
    ),
    path(
        "<uuid:pk>/resubmit/",
        views.ResubmitForReviewView.as_view(),
        name="resubmit_for_review",
    ),
    path(
        "<uuid:pk>/approve/",
        views.ApproveMeetingView.as_view(),
        name="approve_meeting",
    ),
    path(
        "<uuid:pk>/publish/",
        views.PublishMeetingView.as_view(),
        name="publish_meeting",
    ),
    path(
        "<uuid:pk>/close/",
        views.CloseMeetingView.as_view(),
        name="close_meeting",
    ),
    path(
        "<uuid:pk>/reopen/",
        views.ReopenMeetingView.as_view(),
        name="reopen_meeting",
    ),
    path(
        "<uuid:pk>/version-history/",
        views.MeetingVersionHistoryView.as_view(),
        name="meeting_version_history",
    ),
    path(
        "snapshots/<uuid:pk>/",
        views.ApprovedSnapshotDetailView.as_view(),
        name="approved_snapshot_detail",
    ),
    path(
        "snapshots/<uuid:pk>/print/",
        views.SnapshotPrintableView.as_view(),
        name="snapshot_printable",
    ),
]
