# Generated by Django 6.1.1 on 2026-09-23 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(db_index=True, help_text='e.g. accounts.User, accounts.DepartmentMembership, auth.Group', max_length=100)),
                ('record_id', models.CharField(db_index=True, help_text='Primary key (UUID as string or int)', max_length=128)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ROLE', 'Role Change')], db_index=True, max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('target_user', models.ForeignKey(blank=True, help_text='If the record relates to a user, this holds their reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_about', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='audit_audit_record__e657fd_idx'), models.Index(fields=['created_at', 'action'], name='audit_audit_created_c61682_idx'), models.Index(fields=['user', 'action'], name='audit_audit_user_id_ac289d_idx')],
            },
        ),
    ]
