# Generated by Django 6.1.1 on 2026-09-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ROLE', 'Role Change'), ('TRANSITION', 'Workflow Transition'), ('ARCHIVE', 'Archive')], db_index=True, max_length=16),
        ),
    ]
