# Generated by Django 6.1.1 on 2026-09-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ROLE', 'Role Change'), ('TRANSITION', 'Workflow Transition'), ('ARCHIVE', 'Archive'), ('COMPLETE', 'Complete'), ('REOPEN', 'Reopen'), ('CARRY_FORWARD', 'Carry Forward')], db_index=True, max_length=16),
        ),
    ]
