# Generated by Django 6.1.1 on 2026-09-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ROLE', 'Role Change'), ('TRANSITION', 'Workflow Transition'), ('ARCHIVE', 'Archive'), ('COMPLETE', 'Complete'), ('REOPEN', 'Reopen'), ('CARRY_FORWARD', 'Carry Forward'), ('LOCK', 'Lock Record'), ('EXPORT', 'Export Data'), ('SUBMIT', 'Submit for Review'), ('RETURN', 'Return for Correction'), ('RESUBMIT', 'Resubmit for Review'), ('SNAPSHOT', 'Snapshot Created')], db_index=True, max_length=16),
        ),
    ]
