# Generated by Django 6.1.1 on 2026-09-24 01:25

import apps.action_items.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_departmentmembership_is_active_and_more'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated reference, e.g. ACT-2026-0012.', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('URG', 'Urgent')], db_index=True, default='MED', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], db_index=True, default='OPEN', max_length=16)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, help_text='0-100 progress (auto-set 100 on COMPLETED).', validators=[django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('blockers', models.TextField(blank=True, help_text='Current blockers preventing progress.')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps to move this item forward.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('carried_forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='action_items.actionitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='accounts.department')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User responsible for the outcome (same as primary assignee usually).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_action_items', to=settings.AUTH_USER_MODEL)),
                ('source_agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='meetings.agendaitem')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'verbose_name_plural': 'Action Items',
                'ordering': [models.Case(models.When(priority='URG', then=0), models.When(priority='HIGH', then=1), models.When(priority='MED', then=2), models.When(priority='LOW', then=3), default=99), '-due_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary assignee owns the deliverable.')),
                ('is_supporting', models.BooleanField(db_index=True, default=False, help_text='Supporting user (helps but not the owner).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='action_items.actionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action_item__created_at', '-is_primary', '-is_supporting', 'user__username'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.action_items.models._action_item_attachment_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='action_items.actionitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_item_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action_item__created_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemCarryForwardLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_scope_key', models.CharField(db_index=True, default='default', help_text='Hashable key distinguishing different carry-forwards (e.g. include_completed flag).', max_length=100)),
                ('carried_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('carried_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_actions', to=settings.AUTH_USER_MODEL)),
                ('new_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forward_sources', to='action_items.actionitem')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_forward_links', to='action_items.actionitem')),
                ('target_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_forward_links', to='meetings.meeting')),
            ],
            options={
                'verbose_name_plural': 'Action Item Carry Forward Links',
                'ordering': ['-carried_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], max_length=16)),
                ('to_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], max_length=16)),
                ('progress_before', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('progress_after', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('transitioned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='action_items.actionitem')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_item_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Action Item Status Histories',
                'ordering': ['action_item__created_at', '-transitioned_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_snapshot', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], help_text='Item status at the time of this update.', max_length=16)),
                ('progress_snapshot', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.action_items.models._action_update_attachment_path)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='action_items.actionitem')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Action Item Updates',
                'ordering': ['action_item__created_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['status', 'priority', 'due_date'], name='action_item_status_26535a_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['department', 'status', 'due_date'], name='action_item_departm_d6ca09_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['owner', 'status', 'due_date'], name='action_item_owner_i_a2a1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['source_meeting', 'status'], name='action_item_source__9d5749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='actionitemassignee',
            unique_together={('action_item', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='actionitemcarryforwardlink',
            unique_together={('source_item', 'target_meeting', 'target_scope_key')},
        ),
        migrations.AddIndex(
            model_name='actionitemstatushistory',
            index=models.Index(fields=['action_item', 'transitioned_at'], name='action_item_action__e63a98_idx'),
        ),
    ]
