# Generated by Django 6.1.1 on 2026-09-23 23:23

import apps.meetings.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_departmentmembership_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('requires_chair_approval', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Meeting Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('scope_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_categories', to='accounts.department')),
            ],
            options={
                'verbose_name_plural': 'Agenda Categories',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('discussion', models.TextField(blank=True)),
                ('decision', models.TextField(blank=True)),
                ('item_status', models.CharField(choices=[('TBD', 'To Be Discussed'), ('CARRIED', 'Carried Forward'), ('IN_PROGRESS', 'In Progress'), ('DECIDED', 'Decided'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='TBD', max_length=16)),
                ('is_confidential', models.BooleanField(db_index=True, default=False)),
                ('time_allocated_minutes', models.PositiveIntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('carried_forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to_items', to='meetings.agendaitem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='meetings.agendacategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agenda_items', to=settings.AUTH_USER_MODEL)),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='meetings.agendaitem')),
            ],
            options={
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['meeting__start_at', 'order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaItemAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.meetings.models._agenda_attachment_path)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.agendaitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agenda Item Attachments',
                'ordering': ['item__meeting__start_at', 'item__order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated human-friendly reference.', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(help_text='Local meeting start time (timezone-aware).')),
                ('end_at', models.DateTimeField(help_text='Local meeting end time (timezone-aware).')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_UPDATES', 'Open for Department Updates'), ('AGENDA_FINALIZED', 'Agenda Finalized'), ('IN_PROGRESS', 'Meeting In Progress'), ('FOR_REVIEW', 'For Review'), ('RETURNED', 'Returned for Correction'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='If locked, only System/Management Administrator can unlock or transition.')),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.department')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_modified', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.meetingtype')),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['-start_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting'),
        ),
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.meetings.models._meeting_attachment_path)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.meeting')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meeting Attachments',
                'ordering': ['meeting__start_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_invited', models.BooleanField(db_index=True, default=True)),
                ('is_attended', models.BooleanField(db_index=True, default=False)),
                ('rsvp_status', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='PENDING', max_length=10)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('role_at_meeting', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting__start_at', 'user__username'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('OPEN_UPDATES', 'Open for Department Updates'), ('AGENDA_FINALIZED', 'Agenda Finalized'), ('IN_PROGRESS', 'Meeting In Progress'), ('FOR_REVIEW', 'For Review'), ('RETURNED', 'Returned for Correction'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_UPDATES', 'Open for Department Updates'), ('AGENDA_FINALIZED', 'Agenda Finalized'), ('IN_PROGRESS', 'Meeting In Progress'), ('FOR_REVIEW', 'For Review'), ('RETURNED', 'Returned for Correction'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('transitioned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='meetings.meeting')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meeting Status Histories',
                'ordering': ['meeting_id', '-transitioned_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['meeting', 'category', 'order'], name='meetings_ag_meeting_2b22ad_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['meeting', 'is_confidential'], name='meetings_ag_meeting_44a6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['owner', 'item_status'], name='meetings_ag_owner_i_574768_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agendaitem',
            unique_together={('meeting', 'order')},
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting', 'is_invited'], name='meetings_me_meeting_d761a4_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting', 'is_attended'], name='meetings_me_meeting_9cf9d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddIndex(
            model_name='meetingstatushistory',
            index=models.Index(fields=['meeting', 'transitioned_at'], name='meetings_me_meeting_3d1422_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'start_at'], name='meetings_me_status_a0c4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['type', 'start_at'], name='meetings_me_type_id_152f94_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['department', 'start_at'], name='meetings_me_departm_c0d5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['chair', 'start_at'], name='meetings_me_chair_i_1056b2_idx'),
        ),
    ]
