# Generated by Django 6.1.1 on 2026-09-24 03:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentmembership_is_active_and_more'),
        ('action_items', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_links', to='action_items.actionitem')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_links', to='meetings.agendaitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Action Item Links',
                'ordering': ['agenda_item__meeting__start_at', 'agenda_item__order'],
                'abstract': False,
                'indexes': [models.Index(fields=['agenda_item', 'created_at'], name='meetings_ac_agenda__102d9c_idx')],
                'unique_together': {('agenda_item', 'action_item')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedMeetingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(db_index=True)),
                ('trigger', models.CharField(choices=[('SUBMIT', 'Submitted for Review'), ('APPROVE', 'Approved'), ('PUBLISH', 'Published'), ('MANUAL', 'Manual Snapshot')], db_index=True, default='MANUAL', max_length=10)),
                ('payload', models.JSONField(default=dict, help_text='Immutable serialized meeting content at snapshot time.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_snapshots', to='meetings.meeting')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Approved Meeting Snapshots',
                'ordering': ['meeting_id', '-version'],
                'abstract': False,
                'indexes': [models.Index(fields=['meeting', 'trigger', 'version'], name='meetings_ap_meeting_3f3281_idx')],
                'unique_together': {('meeting', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_state', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned for Correction'), ('ACCEPTED', 'Accepted by Reviewer')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('missing_info', models.TextField(blank=True)),
                ('management_remarks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_submissions', to='accounts.department')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_submissions', to='meetings.meeting')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Department Submissions',
                'ordering': ['meeting__start_at', 'department__name'],
                'abstract': False,
                'indexes': [models.Index(fields=['meeting', 'submission_state'], name='meetings_de_meeting_b40fb0_idx'), models.Index(fields=['department', 'submission_state'], name='meetings_de_departm_627c3b_idx')],
                'unique_together': {('meeting', 'department')},
            },
        ),
        migrations.CreateModel(
            name='MinutesSectionSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('OPENING', 'Opening Remarks'), ('DEPT_UPDATES', 'Department Updates'), ('ACTION_ITEMS', 'Action Items Review'), ('SALES', 'Sales Performance'), ('OLD_BUSINESS', 'Old Business'), ('NEW_BUSINESS', 'New Business'), ('OTHER', 'Other Topics')], max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=128)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_specs', to='meetings.meetingtype')),
            ],
            options={
                'verbose_name_plural': 'Minutes Section Specs',
                'ordering': ['meeting_type_id', 'order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['meeting_type', 'order'], name='meetings_mi_meeting_ceb18c_idx')],
                'unique_together': {('meeting_type', 'section_type')},
            },
        ),
    ]
